# -*- mode: python ; coding: utf-8 -*-
# Windows-specific build configuration for Song Editor 3

block_cipher = None

a = Analysis(
    ['song_editor/app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('song_editor/ui', 'song_editor/ui'),
        ('song_editor/core', 'song_editor/core'),
        ('song_editor/models', 'song_editor/models'),
        ('song_editor/export', 'song_editor/export'),
        ('song_editor/processing', 'song_editor/processing'),
        ('song_editor/services', 'song_editor/services'),
    ],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'librosa',
        'soundfile',
        'numpy',
        'pyloudnorm',
        'noisereduce',
        'sounddevice',
        'faster_whisper',
        'openai_whisper',
        'cmudict',
        'pronouncing',
        'nltk',
        'collections',
        'torch',
        'torchaudio',
        'tensorflow',
        'ctranslate2',
        'transformers',
        'basic_pitch',
        'crepe',
        'librosa.feature',
        'librosa.beat',
        'librosa.onset',
        'librosa.util',
        'librosa.core',
        'librosa.sequence',
        'librosa.segment',
        'librosa.spectral',
        'librosa.tempo',
        'librosa.yin',
        'librosa.pyin',
        'librosa.harmonic',
        'librosa.percussive',
        'librosa.decompose',
        'librosa.effects',
        'librosa.filters',
        'librosa.phase',
        'librosa.pitch',
        'librosa.rhythm',
        'librosa.similarity',
    ],
    excludes=[
        'PyQt5',
        'PyQt6',
        'PySide2',
        'tkinter',
        'matplotlib.backends.backend_tkagg',
        'whisperx',
        'mlx_whisper',
        'demucs',
        'pyannote',
        'lightning_fabric',
        'pytorch_lightning',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes_binaries=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Song_Editor_3_Windows',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='song_editor/ui/icons/app_icon.ico',  # Windows icon
)
